export const ENTITIES = [
  { key:"projects", label:"العقارات", table:"projects", order:"sort_order", title:"i18n.title", fields:[
    {n:"code",t:"text",l:"الكود",req:true},
    {n:"city_key",t:"select",l:"المدينة",options:"taxonomy:city"},
    {n:"type_key",t:"select",l:"النوع",options:"taxonomy:property_type"},
    {n:"status",t:"select",l:"الحالة",options:["available","reserved","sold","soon"]},
    {n:"sold",t:"number",l:"نسبة البيع"},
    {n:"price_min",t:"number",l:"سعر من"},{n:"price_max",t:"number",l:"سعر إلى"},
    {n:"area",t:"text",l:"المساحة"},{n:"beds_min",t:"number",l:"غرف من"},{n:"beds_max",t:"number",l:"غرف إلى"},
    {n:"featured",t:"bool",l:"مميّز"},{n:"sort_order",t:"number",l:"الترتيب"},
    {n:"image_url",t:"image",l:"الصورة"},
    {n:"brochure_url",t:"file",l:"البروشور (PDF)"},
    {n:"map_lat",t:"number",l:"إحداثي العرض (Lat)",hint:"اختياري — كليك يمين على الموقع في Google Maps ثم انسخ الرقم الأول"},
    {n:"map_lng",t:"number",l:"إحداثي الطول (Lng)",hint:"اختياري — الرقم الثاني من الإحداثيات"},
    {n:"i18n.title",t:"i18n-text",l:"العنوان"},{n:"i18n.district",t:"i18n-text",l:"الحي"},
    {n:"i18n.description",t:"i18n-rich",l:"الوصف"} ]},
  { key:"news", label:"المدونة", table:"news", order:"published_at", title:"i18n.title",
    workflow:"draft", slugFrom:"i18n.title", fields:[
    {n:"i18n.title",t:"i18n-text",l:"العنوان"},
    {n:"image_url",t:"image",l:"الصورة"},
    {n:"i18n.body",t:"i18n-rich",l:"المقال"} ]},
  { key:"partners", label:"الشركاء", table:"partners", order:"sort_order", title:"i18n.name", fields:[
    {n:"logo_url",t:"image",l:"الشعار",hint:"SVG (مفضّل) أو PNG بخلفية شفافة · شعار عرضي ~240×120px · أقصى حجم 200KB",spec:{maxKB:200,maxW:600,maxH:400,recW:240,recH:120}},{n:"sort_order",t:"number",l:"الترتيب"},
    {n:"i18n.name",t:"i18n-text",l:"الاسم"} ]},
  { key:"stats", label:"الأرقام", table:"stats", order:"sort_order", title:"i18n.label", fields:[
    {n:"value",t:"number",l:"القيمة",req:true},{n:"suffix",t:"text",l:"اللاحقة"},
    {n:"sort_order",t:"number",l:"الترتيب"},{n:"i18n.label",t:"i18n-text",l:"العنوان"} ]},
  { key:"social_links", label:"السوشيال", table:"social_links", order:"sort_order", title:"platform", fields:[
    {n:"platform",t:"select",l:"المنصّة",options:["instagram","x","tiktok","snapchat","linkedin","youtube","facebook"]},
    {n:"url",t:"text",l:"الرابط",req:true},{n:"enabled",t:"bool",l:"مفعّل"},{n:"sort_order",t:"number",l:"الترتيب"} ]},
  { key:"contact", label:"التواصل", table:"contact", order:"id", single:true, title:"email", fields:[
    {n:"whatsapp",t:"text",l:"واتساب (دولي بلا +)"},{n:"email",t:"text",l:"البريد"},{n:"phone",t:"text",l:"الهاتف"},
    {n:"map_url",t:"text",l:"رابط الخريطة"},
    {n:"i18n.address",t:"i18n-text",l:"العنوان"},{n:"i18n.hours",t:"i18n-text",l:"ساعات العمل"} ]},
  { key:"pages", label:"الصفحات", table:"pages", order:"key", pk:"key", title:"key", fields:[
    {n:"i18n.title",t:"i18n-text",l:"العنوان"},{n:"i18n.body",t:"i18n-rich",l:"النص"} ]},
  { key:"home_content", label:"الرئيسية", table:"home_content", order:"id", single:true, title:"id", fields:[
    {n:"hero_image_url",t:"image",l:"صورة خلفية الهيرو"},
    {n:"i18n.hero_title",t:"i18n-text",l:"الهيرو — العنوان"},
    {n:"i18n.hero_lead",t:"i18n-rich",l:"الهيرو — الوصف"},
    {n:"i18n.hero_cta1",t:"i18n-text",l:"الهيرو — زر رئيسي"},
    {n:"i18n.hero_cta2",t:"i18n-text",l:"الهيرو — زر ثانوي"},
    {n:"i18n.search_eyebrow",t:"i18n-text",l:"البحث — العنوان الصغير"},
    {n:"i18n.svc_eyebrow",t:"i18n-text",l:"الخدمات — العنوان الصغير"},
    {n:"i18n.svc_head",t:"i18n-text",l:"الخدمات — العنوان"},
    {n:"i18n.svc1_title",t:"i18n-text",l:"خدمة ١ — العنوان"},{n:"i18n.svc1_desc",t:"i18n-rich",l:"خدمة ١ — الوصف"},
    {n:"i18n.svc2_title",t:"i18n-text",l:"خدمة ٢ — العنوان"},{n:"i18n.svc2_desc",t:"i18n-rich",l:"خدمة ٢ — الوصف"},
    {n:"i18n.svc3_title",t:"i18n-text",l:"خدمة ٣ — العنوان"},{n:"i18n.svc3_desc",t:"i18n-rich",l:"خدمة ٣ — الوصف"},
    {n:"i18n.feat_eyebrow",t:"i18n-text",l:"المميّزة — العنوان الصغير"},
    {n:"i18n.feat_head",t:"i18n-text",l:"المميّزة — العنوان"},
    {n:"i18n.feat_link",t:"i18n-text",l:"المميّزة — رابط (كل المشاريع)"},
    {n:"i18n.partners_eyebrow",t:"i18n-text",l:"الشركاء — العنوان الصغير"},
    {n:"i18n.why_eyebrow",t:"i18n-text",l:"لماذا — العنوان الصغير"},
    {n:"i18n.why_head",t:"i18n-text",l:"لماذا — العنوان"},
    {n:"i18n.why_lead",t:"i18n-rich",l:"لماذا — الوصف"},
    {n:"i18n.why_cta",t:"i18n-text",l:"لماذا — زر"},
    {n:"i18n.why1_title",t:"i18n-text",l:"سبب ١ — العنوان"},{n:"i18n.why1_desc",t:"i18n-rich",l:"سبب ١ — الوصف"},
    {n:"i18n.why2_title",t:"i18n-text",l:"سبب ٢ — العنوان"},{n:"i18n.why2_desc",t:"i18n-rich",l:"سبب ٢ — الوصف"},
    {n:"i18n.why3_title",t:"i18n-text",l:"سبب ٣ — العنوان"},{n:"i18n.why3_desc",t:"i18n-rich",l:"سبب ٣ — الوصف"},
    {n:"i18n.cta_head",t:"i18n-text",l:"شريط CTA — العنوان"},
    {n:"i18n.cta_lead",t:"i18n-rich",l:"شريط CTA — الوصف"},
    {n:"i18n.cta_primary",t:"i18n-text",l:"شريط CTA — زر رئيسي"},
    {n:"i18n.cta_wa",t:"i18n-text",l:"شريط CTA — زر واتساب"} ]},
  { key:"about_content", label:"صفحة من نحن", table:"about_content", order:"id", single:true, title:"id", fields:[
    {n:"i18n.about_eyebrow",     t:"i18n-text", l:"البانر — العنوان الصغير"},
    {n:"i18n.about_title",       t:"i18n-text", l:"البانر — العنوان"},
    {n:"i18n.about_lead",        t:"i18n-rich", l:"البانر — الوصف"},
    {n:"i18n.about_story_eyebrow", t:"i18n-text", l:"القصة — العنوان الصغير"},
    {n:"i18n.about_story_head",  t:"i18n-text", l:"القصة — العنوان"},
    {n:"i18n.about_story_p1",    t:"i18n-rich", l:"القصة — فقرة ١"},
    {n:"i18n.about_story_p2",    t:"i18n-rich", l:"القصة — فقرة ٢"},
    {n:"i18n.about_mission_eyebrow", t:"i18n-text", l:"المهمّة — العنوان الصغير"},
    {n:"i18n.about_mission_text",t:"i18n-rich", l:"المهمّة — النص"},
    {n:"i18n.about_vision_eyebrow", t:"i18n-text", l:"الرؤية — العنوان الصغير"},
    {n:"i18n.about_vision_text", t:"i18n-rich", l:"الرؤية — النص"},
    {n:"i18n.about_steps_eyebrow", t:"i18n-text", l:"الخطوات — العنوان الصغير"},
    {n:"i18n.about_steps_head",  t:"i18n-text", l:"الخطوات — العنوان"},
    {n:"i18n.about_step1_title", t:"i18n-text", l:"خطوة ١ — العنوان"},
    {n:"i18n.about_step1_desc",  t:"i18n-rich", l:"خطوة ١ — الوصف"},
    {n:"i18n.about_step2_title", t:"i18n-text", l:"خطوة ٢ — العنوان"},
    {n:"i18n.about_step2_desc",  t:"i18n-rich", l:"خطوة ٢ — الوصف"},
    {n:"i18n.about_step3_title", t:"i18n-text", l:"خطوة ٣ — العنوان"},
    {n:"i18n.about_step3_desc",  t:"i18n-rich", l:"خطوة ٣ — الوصف"},
    {n:"i18n.about_step4_title", t:"i18n-text", l:"خطوة ٤ — العنوان"},
    {n:"i18n.about_step4_desc",  t:"i18n-rich", l:"خطوة ٤ — الوصف"},
    {n:"i18n.about_values_eyebrow", t:"i18n-text", l:"القيم — العنوان الصغير"},
    {n:"i18n.about_values_head", t:"i18n-text", l:"القيم — العنوان"},
    {n:"i18n.about_val1_title",  t:"i18n-text", l:"قيمة ١ — العنوان"},
    {n:"i18n.about_val1_desc",   t:"i18n-rich", l:"قيمة ١ — الوصف"},
    {n:"i18n.about_val2_title",  t:"i18n-text", l:"قيمة ٢ — العنوان"},
    {n:"i18n.about_val2_desc",   t:"i18n-rich", l:"قيمة ٢ — الوصف"},
    {n:"i18n.about_val3_title",  t:"i18n-text", l:"قيمة ٣ — العنوان"},
    {n:"i18n.about_val3_desc",   t:"i18n-rich", l:"قيمة ٣ — الوصف"},
    {n:"i18n.about_val4_title",  t:"i18n-text", l:"قيمة ٤ — العنوان"},
    {n:"i18n.about_val4_desc",   t:"i18n-rich", l:"قيمة ٤ — الوصف"},
    {n:"i18n.about_val5_title",  t:"i18n-text", l:"قيمة ٥ — العنوان"},
    {n:"i18n.about_val5_desc",   t:"i18n-rich", l:"قيمة ٥ — الوصف"},
    {n:"i18n.about_quote",       t:"i18n-rich", l:"الاقتباس"},
    {n:"i18n.about_cta_head",    t:"i18n-text", l:"شريط CTA — العنوان"},
    {n:"i18n.about_cta_btn",     t:"i18n-text", l:"شريط CTA — الزر"},
  ]},
  { key:"site_chrome", label:"الهيدر والفوتر", table:"site_chrome", order:"id", single:true, title:"id", fields:[
    {n:"i18n.nav_home",t:"i18n-text",l:"القائمة — الرئيسية"},
    {n:"i18n.nav_projects",t:"i18n-text",l:"القائمة — المشاريع"},
    {n:"i18n.nav_services",t:"i18n-text",l:"القائمة — الخدمات"},
    {n:"i18n.nav_about",t:"i18n-text",l:"القائمة — من نحن"},
    {n:"i18n.nav_news",t:"i18n-text",l:"القائمة — المدونة"},
    {n:"i18n.nav_contact",t:"i18n-text",l:"القائمة — تواصل"},
    {n:"i18n.nav_cta",t:"i18n-text",l:"القائمة — زر الاستشارة"},
    {n:"i18n.topbar_city",t:"i18n-text",l:"الشريط العلوي — المدينة"},
    {n:"i18n.footer_tag",t:"i18n-rich",l:"الفوتر — الوصف"},
    {n:"i18n.footer_explore_head",t:"i18n-text",l:"الفوتر — عنوان تصفّح"},
    {n:"i18n.footer_contact_head",t:"i18n-text",l:"الفوتر — عنوان تواصل"},
    {n:"i18n.footer_bottom",t:"i18n-text",l:"الفوتر — الشريط السفلي"},
    {n:"i18n.footer_rights",t:"i18n-text",l:"الفوتر — الحقوق"} ]},
  { key:"site_theme", label:"المظهر", table:"site_theme", order:"id", single:true, title:"id", fields:[
    {n:"font_preset",t:"select",l:"الخط",options:["classic","modern","elegant","simple"],
      hint:"classic=كلاسيكي · modern=عصري · elegant=أنيق · simple=بسيط"},
    {n:"accent_preset",t:"select",l:"لون الهوية",options:["gold","green","navy","charcoal","burgundy"],
      hint:"gold=ذهبي · green=أخضر · navy=كحلي · charcoal=فحمي · burgundy=نبيذي"} ]},
];
